# Webserverver with Dispatcher module for AEM author and/or publish instance
# Generates general dispatcher configuration

variants:

# Dispatcher in front of Authoring instance
- variant: aem-author

# Disaptcher for publish instances - configure a tenant for each vhost
- variant: aem-publish
  config:
    
    httpd:
      # Default server name to tenant name on publish
      serverName: ${tenant}

    dispatcher:
      renderInstance:
        port: 4503
      
      # dispatcher.any filter rules
      filter:
      - url: /.*
        type: deny
      # open consoles (access is controlled in httpd config)
      - url: /(admin|crx|system)(/.*)?
        type: allow
      # Allow non-public content directories
      - url: /content(/.*)?
        type: allow
      # Enable extensions in non-public content directories
      - extension: (css|gif|ico|js|png|swf|jpe?g)
        type: allow
      # Enable features 
      - url: /libs/cq/personalization(/.*)?
        type: allow
      - url: /etc/(clientlibs|designs)(/.*)?
        type: allow
      # Deny content grabbing, on all accessible pages
      - selectors: ((sys|doc)view|query|[0-9-]+)
        extension: (json|xml)
        type: deny
      # Deny content grabbing for /content
      - path: /content(/.*)?
        selectors: (feed|rss|pages|languages|blueprint|infinity|tidy|form)
        extension: (json|xml|html)
        type: deny

# Mixin variant to support HTTPS access
- variant: ssl
  config:
    httpd:
      modules:
      - _merge_
      - ssl

templateDir: aem-dispatcher

files:

# --- common ---

# global httpd dispatcher config
- file: dispatcher.conf
  dir: conf.d
  template: common/dispatcher.conf.hbs

# global dispatcher config
- file: dispatcher.any
  dir: conf.d
  template: common/dispatcher.any.hbs

# load snippte for dispatcher module
- file: dispatcher.load
  dir: mods-available
  template: common/dispatcher.load.hbs

# --- author ---

# Dispatcher configuration
- file: dispatcher_author.any
  dir: conf.d
  variants:
  - aem-author*
  template: author/dispatcher_author.any.hbs

# httpd vhost (HTTP)
- file: vhost_author.conf
  dir: sites-available
  variants:
  - aem-author*
  template: author/vhost_author.conf.hbs

# httpd vhost (HTTPS)
- file: vhost_author.ssl.conf
  dir: sites-available
  variants:
  - aem-author*
  - ssl*
  template: author/vhost_author.ssl.conf.hbs

# --- publish ---

# Dispatcher configuration
- file: dispatcher_publish.any
  dir: conf.d
  variants:
  - aem-publish*
  template: publish/dispatcher_publish.any.hbs

# httpd vhost per tenant (HTTP)
- file: vhost_publish_${tenant}.conf
  dir: sites-available
  variants:
  - aem-publish*
  template: publish/vhost_publish_tenant.conf.hbs
  # Mulitply file for each tenant that has the given roles
  multiply: tenant

# httpd vhost per tenant (HTTPS)
- file: vhost_publish_${tenant}.ssl.conf
  dir: sites-available
  variants:
  - aem-publish*
  - ssl*
  condition: ${httpd.ssl.certificateFile}
  template: publish/vhost_publish_tenant.ssl.conf.hbs
  # Mulitply file for each tenant that has the given roles
  multiply: tenant


config:

  httpd:

    # Modules to be activated in httpd as they are used in the templates. Use names that can be used with a2enmod.
    modules:
    - dispatcher
    - rewrite
    - headers

    # Server and alias names and - optionally - an alternative server names for SSL.
    # On publish instances the server name defaults to the tenant name.
    serverName:
    serverNameSsl: ${httpd.serverName}
    serverAliasNames:
    serverAliasNamesSsl: ${httpd.serverAliasNames}

    # Access restrictions
    accessRestriction:

      # Allow access to adminstrative areas only to certain sources (same on author and publish)
      locationFilter:
      - location: /admin
        type: deny_allow_admin
      - location: /crx
        type: deny_allow_admin
      - location: /system
        type: deny_allow_admin
      - locationMatch: /system/sling/logout.*
        type: allow

      # Allow access to administrative URLs like /crx, /system/console etc. only from these sources
      #adminAccessFromIp: 10.0.0.0/255.0.0.0
      #adminAccessFromHost: www.example.org

      # Allow dispatcher flush only from these sources
      #dispatcherFlushFromIp: 127.0.0.1
      #dispatcherFlushFromHost: localhost

    # Redirecting from "/" (only publish dispatcher)
    rootRedirect:
      #url: /en.html
      httpStatus: 301

    # Configure CORS header to be sent to the client (only on publish dispatcher)
    corsHeader:
      enabled: true
      # Generate them by default only for font-related files
      locationMatch: "\\.(svg|eot|ttf|woff)"
      # If set to true always "*" is sent as 'Access-Control-Allow-Origin' header
      # If set to false only the requesting host is all if it is in the hostWhiteList (or this list is empty), and not in the hostBlackList
      allowAllHosts: true
      #hostWhiteList:
      #- www.host1.com
      #- www.host2.com

    # SSL configuration
    ssl:
      # SSL Certificate files
      #certificateFile: /path/to/sslCertificateFile
      #certificateKeyFile: /path/to/sslCertificateKeyFile
      #caCertificatePath: /path/to/sslCACertificates
      #caCertificateFile: /path/to/sslCACertificateFile

      # If set to true all requests are redirectd to HTTPS and HSTS is enabled
      enforce: false

  dispatcher:
    
    # Module binary for AEM dispatcher
    moduleFile: modules/mod_dispatcher.so
    
    # Dispatcher cache root path
    #cacheRootPath: /path/to/dispatcher/cache
    
    # Hostname and port of AEM instance
    renderInstance:
      host: localhost
      port: 4502
    
    # Forward client headers from dispatcher to AEM instance
    forwardClientHeaders:    
    - "*"

    # dispatcher.any filter rules
    filter:
    - url: /.*
      type: allow

    # Stars file level for dispatcher (only on publish dispatcher)
    #statFilesLevel: 3
    
    # Only for authoring dispatcher: whether assets should be cached
    cacheDamAssets: false

  sling:

    # Configure Sling Mapping for URL shortening of content paths
    mapping:
      # Content root path which is stripped off
      #rootPath: /content/path
      # By default, only access to paths shortened via Sling Mapping are allowed. Set this to true to also allow unshortened paths.
      #allowUnshortenedPath: false



# Example tenant configuration. Tenant name = primary host name/server name
#config:
#  httpd:
#    serverName: ${tenant}
#    serverNameSsl:
#    serverAliasNames:
#    - alias1
#    - alias2
#    rootRedirect.url: /en.html
#    ssl:
#      certificateFile: /path/to/sslCertificateFile
#      certificateKeyFile: /path/to/sslCertificateKeyFile
#      caCertificateFile: /path/to/sslCACertificateFile
#      caCertificatePath: /path/to/sslCACertificates
#  dispatcher:
#    tenantSpecificVHostConfig: |
#      Custom Config Line 1
#      Custom Config Line 2
#  sling.mapping.rootPath: /content/path
