# Adobe Experience Manager (AEM) Instance.
# AEM quickstart runs directly from command line with embedded Jetty Servlet Container.

variants:
- variant: aem-author
- variant: aem-publish
  config:
    quickstart:
      port: 4503
      runmodes:
      - publish
      - nosamplecontent

templateDir: aem-cms

files:

# Sling Mapping for Publish Instance
- file: aem-cms-publish-slingmapping.json
  dir: packages
  template: aem-cms-publish-slingmapping.json.hbs
  variants:
  - aem-publish
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: aem-cms-publish-slingmapping
      rootPath: /etc/map
      filters:
      - filter: /etc/map
        rules:
        - rule: exclude
          pattern: /etc/map
        - rule: include
          pattern: /etc/map/.*
        - rule: exclude
          pattern: /etc/map/http
        - rule: include
          pattern: /etc/map/http/.*
        - rule: exclude
          pattern: /etc/map/http/AppMeasurementBridge

# AEM Replication (Author)
- file: aem-cms-author-replicationagents.json
  dir: packages
  template: aem-cms-author-replicationagents.json.hbs
  variants:
  - aem-author
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: aem-cms-author-replicationagents
      rootPath: /etc/replication
      filters:
      - filter: /etc/replication/agents.author
        # Uncomment this to keep the built-in special agents
        #rules:
        #- rule: exclude
        #  pattern: /etc/replication/agents\.author/(flush|publish_reverse|static|test_and_target|dynamic_media_replication|s7delivery|offloading_outbox)

# AEM Replication (Publish)
- file: aem-cms-publish-replicationagents.json
  dir: packages
  template: aem-cms-publish-replicationagents.json.hbs
  variants:
  - aem-publish
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: aem-cms-publish-replicationagents
      rootPath: /etc/replication
      filters:
      - filter: /etc/replication/agents.publish
        # Uncomment this to keep the built-in special agents
        #rules:
        #- rule: exclude
        #  pattern: /etc/replication/agents\.publish/(outbox|s7delivery)

# Minimal "DAM Update Asset" Workfow (Author)
- file: aem-cms-author-dam-update-asset-workflow-minimal.json
  dir: packages
  template: aem-cms-author-dam-update-asset-workflow-minimal.json.hbs
  variants:
  - aem-author
  condition: "${workflow.useMinimalDamUpdateAssetWorkflow}"
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: aem-cms-author-dam-update-asset-workflow-minimal
      rootPath: /etc/workflow/models/dam/update_asset

# AEM Quickstart start script
- file: start
  dir: bin
  template: start.hbs
  fileHeader: unixShellScript


# Defines configuration parameters and default values
config:
  contentPackage:
    group: conga-aem-cms
    version: "${version}"

  jvm:
    path: /path/to/java
    heapspace:
      min: 2048m
      max: 2048m
    permgenspace:
      max: 256m
    #timezone: Europe/Berlin
    #args: additional custom JVM args

  quickstart:
    port: 4502
    runmodes:
    - author
    - nosamplecontent

  replication:
    author:
      publishTargets:
      #- name: publish1
      #  url: http://localhost:4503
      #  transportUser: admin
      #  # Has to be encrypted with the correct key, see http://www.wemblog.com/2012/03/how-to-use-crypto-support-in-cq55.html
      #  transportPassword: "{bb696f1ac8643072c0bcf45dbc66d782e37a5ed8bc3f55fc51c012fc469bf6cc}"
      flushTarget:
        #name: dispatcherAuthor1
        #url: http://localhost:8000
    publish:
      flushTarget:
        #name: dispatcherPublish1
        #url: http://localhost:8000

  workflow:
    useMinimalDamUpdateAssetWorkflow: true


# Example tenant configuration. Tenant name = primary host name/server name
#config:
#  serverNameSsl:
#  aliasNames:
#  - alias1
#  - alias2
#  slingMappingPath: /content/path
